services:
  freqtrade:
    image: freqtrade:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: duo-ai-tradingbot
    volumes:
      - "../user_data:/freqtrade/user_data"
      - "../config:/freqtrade/config"
      - "../strategies:/freqtrade/user_data/strategies"
      - "../core:/freqtrade/core"
    environment:
      - "PYTHONPATH=/freqtrade"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/config/config.json
      --strategy DUOAI_Strategy
